# Generated by Django 3.2.13 on 2023-03-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf_center', '0001_initial'),
        ('host', '0002_pkeymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='conf_center.environment', verbose_name='从属环境'),
        ),
    ]
