# Generated by Django 3.2.13 on 2023-03-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='devops_user',
        ),
    ]
